### ISSUE TITLE
Build Dashboard for Client CMS

### ISSUE THREAD

**Issue by FinCrestLabs** [FinCrestLabs/Corporate_Client_Portal#1]
We need to create a user-friendly dashboard for the Client Content Management System (CMS) that allows users to easily manage client data, view analytics, and navigate through various CMS features. This dashboard will be a central hub for all CMS functionalities, providing a clear overview and access to key features.

Key Features:

- Client Overview: Display a list of clients with relevant details such as name, status, and recent activities.
- Responsive Design: Ensure the dashboard is fully responsive and works across all devices.

**Comment by ninadvyas** [comment]
Can you assign me this issue?
