### ISSUE TITLE
Auth API create credentials for new users - clients/admin

### ISSUE THREAD

**Issue by FinCrestLabs** [FinCrestLabs/Corporate_Client_Portal#6]
Major Base API related to Auth and Assigning Credentials to Clients' Users

- [ ] -  Assign Credentials: Develop an endpoint to assign and manage user credentials for different clients.
- [ ] -  Role-Based Access Control: Define roles and permissions for managing access control across different users.

**Comment by Buddha-11** [comment]
@FinCrestLabs Would like to work on this  , please provide more details about what kind of roles are required and to what level each role should have the access to.

**Comment by ptlnisarg31** [comment]
@FinCrestLabs i have done with the api in my Fork so please assign me! you can validate also..

**Comment by FinCrestLabs** [comment]
> @FinCrestLabs Would like to work on this , please provide more details about what kind of roles are required and to what level each role should have the access to.
@Buddha-11 
Keep updated with new issues ! provide details about your preferences.
Tech stack -

- [ ] Frontend : NextJS,ShadCN
- [ ] Bakcned : Node,Express,Mysql,FileSystem
- [ ] Integration/System Design
